#!/usr/bin/env bash
set -e

IMAGE_NAME=demo_spring_react_minimal_dev

docker build -t "${IMAGE_NAME}" - < Dockerfile

IMAGE_ID=$(docker images -q "${IMAGE_NAME}")
CONTAINER_NAME="${IMAGE_NAME}_${IMAGE_ID}"

if [ ! "$(docker ps -aq -f "name=${CONTAINER_NAME}")" ]; then
  docker create -p 8080:8080 -v "$(pwd):/app" -it --name "${CONTAINER_NAME}" "${IMAGE_ID}" /bin/bash
fi

docker start -a -i "${CONTAINER_NAME}"

